export const typeRecord: Record<string, string> = {
  newstock_onlist: '新股上市',
  newstock_apply: '新股申购',
  CNV: '可转债',
  kzzsg: '可转债申购和上市',
  CBDIV: '正股分红',
  cnreits: 'REITs',
  FUND: '基金',
  BOND: '债券',
  STOCK: '股票',
  OTHER: '其它',
  newbond_apply: '新债申购',
  newbond_onlist: '新债上市',
  diva: 'A股分红',
  divhk: 'H股分红',
  idxfut: '股指期货',
  idxopt: '股指期权',
};

export const priorityRecord: Record<string, number> = {
  newstock_onlist: 9,
  newstock_apply: 9,
  CNV: 3,
  kzzsg: 8,
  CBDIV: 4,
  cnreits: 1,
  FUND: 3,
  BOND: 2,
  STOCK: 4,
  OTHER: 1,
  newbond_apply: 6,
  newbond_onlist: 6,
  diva: 4,
  divhk: 3,
  idxfut: 0,
  idxopt: 0,
};
