<script lang="ts">
  import { ShTable, type TableDataList, type TableThead } from '@istock-shell/ui';

  const thead: TableThead = [
    { value: '', dataKey: 'index' },
    { value: 'Name', dataKey: 'name' },
    { value: 'Job', dataKey: 'job' },
    { value: 'company', dataKey: 'company' },
    { value: 'location', dataKey: 'location' },
    { value: 'Last Login', dataKey: 'lastLogin' },
    { value: 'Favorite Color', dataKey: 'color' },
  ];
  const tbody: TableDataList = [
    {
      index: 1,
      name: 'Cy Ganderton',
      job: 'Quality Control Specialist',
      company: 'Littel, Schaden and Vandervort',
      location: 'Canada',
      lastLogin: '12/16/2020',
      color: 'Blue',
    },
    {
      index: 2,
      name: 'Hart Hagerty',
      job: 'Desktop Support Technician',
      company: 'Zemlak, Daniel and Leannon',
      location: 'United States',
      lastLogin: '12/5/2020',
      color: 'Purple',
    },
    {
      index: 3,
      name: 'Brice Swyre',
      job: 'Tax Accountant',
      company: 'Carroll Group',
      location: 'China',
      lastLogin: '8/15/2020',
      color: 'Red',
    },
    {
      index: 4,
      name: 'Marjy Ferencz',
      job: 'Office Assistant I',
      company: 'Rowe-Schoen',
      location: 'Russia',
      lastLogin: '3/25/2021',
      color: 'Crimson',
    },
    {
      index: 5,
      name: 'Yancy Tear',
      job: 'Community Outreach Specialist',
      company: 'Wyman-Ledner',
      location: 'Brazil',
      lastLogin: '5/22/2020',
      color: 'Indigo',
    },
    {
      index: 6,
      name: 'Irma Vasilik',
      job: 'Editor',
      company: 'Wiza, Bins and Emard',
      location: 'Venezuela',
      lastLogin: '12/8/2020',
      color: 'Purple',
    },
    {
      index: 7,
      name: 'Meghann Durtnal',
      job: 'Staff Accountant IV',
      company: 'Schuster-Schimmel',
      location: 'Philippines',
      lastLogin: '2/17/2021',
      color: 'Yellow',
    },
    {
      index: 8,
      name: 'Sammy Seston',
      job: 'Accountant I',
      company: "O'Hara, Welch and Keebler",
      location: 'Indonesia',
      lastLogin: '5/23/2020',
      color: 'Crimson',
    },
    {
      index: 9,
      name: 'Lesya Tinham',
      job: 'Safety Technician IV',
      company: 'Turner-Kuhlman',
      location: 'Philippines',
      lastLogin: '2/21/2021',
      color: 'Maroon',
    },
    {
      index: 10,
      name: 'Zaneta Tewkesbury',
      job: 'VP Marketing',
      company: 'Sauer LLC',
      location: 'Chad',
      lastLogin: '6/23/2020',
      color: 'Green',
    },
    {
      index: 11,
      name: 'Andy Tipple',
      job: 'Librarian',
      company: 'Hilpert Group',
      location: 'Poland',
      lastLogin: '7/9/2020',
      color: 'Indigo',
    },
    {
      index: 12,
      name: 'Sophi Biles',
      job: 'Recruiting Manager',
      company: 'Gutmann Inc',
      location: 'Indonesia',
      lastLogin: '2/12/2021',
      color: 'Maroon',
    },
    {
      index: 13,
      name: 'Florida Garces',
      job: 'Web Developer IV',
      company: 'Gaylord, Pacocha and Baumbach',
      location: 'Poland',
      lastLogin: '5/31/2020',
      color: 'Purple',
    },
    {
      index: 14,
      name: 'Maribeth Popping',
      job: 'Analyst Programmer',
      company: 'Deckow-Pouros',
      location: 'Portugal',
      lastLogin: '4/27/2021',
      color: 'Aquamarine',
    },
    {
      index: 15,
      name: 'Moritz Dryburgh',
      job: 'Dental Hygienist',
      company: 'Schiller, Cole and Hackett',
      location: 'Sri Lanka',
      lastLogin: '8/8/2020',
      color: 'Crimson',
    },
    {
      index: 16,
      name: 'Reid Semiras',
      job: 'Teacher',
      company: 'Sporer, Sipes and Rogahn',
      location: 'Poland',
      lastLogin: '7/30/2020',
      color: 'Green',
    },
    {
      index: 17,
      name: 'Alec Lethby',
      job: 'Teacher',
      company: 'Reichel, Glover and Hamill',
      location: 'China',
      lastLogin: '2/28/2021',
      color: 'Khaki',
    },
    {
      index: 18,
      name: 'Aland Wilber',
      job: 'Quality Control Specialist',
      company: 'Kshlerin, Rogahn and Swaniawski',
      location: 'Czech Republic',
      lastLogin: '9/29/2020',
      color: 'Purple',
    },
    {
      index: 19,
      name: 'Teddie Duerden',
      job: 'Staff Accountant III',
      company: 'Pouros, Ullrich and Windler',
      location: 'France',
      lastLogin: '10/27/2020',
      color: 'Aquamarine',
    },
    {
      index: 20,
      name: 'Lorelei Blackstone',
      job: 'Data Coordinator',
      company: 'Witting, Kutch and Greenfelder',
      location: 'Kazakhstan',
      lastLogin: '6/3/2020',
      color: 'Red',
    },
  ];
</script>

<div class="overflow-x-auto">
  <ShTable {thead} {tbody} tfoot={[{ list: thead }]} size="xs" />
</div>
